name: "新内容请求"
description: 进一步完善指南，给生存指南添加新内容！
labels: ["新点子 enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        感谢你向我们提出宝贵的建议！我们将认真考虑并尽快给出反馈。
  - type: textarea
    id: feature-description
    attributes:
      label: "请描述你想要添加的新内容"
      placeholder: "在这里详细描述你想要添加的新内容..."
    validations:
      required: true
  - type: textarea
    id: additional-text
    attributes:
      label: "补充说明"
      placeholder: "在这里详细描述你想要添加的新内容..."
    validations:
      required: false
  - type: input
    id: identification
    attributes:
      label: 你的班级或年级（非必填）
      description: 如果你的建议得到我们采纳，你的名字将出现在最新的生存指南中。
      placeholder: 请输入内容
    validations:
      required: false
  - type: checkboxes
    id: checkboxes
    attributes:
      label: Validations
      description: 在提交议题之前，请确认以下事宜
      options:
        - label: 我确认这是最新版中没有涉及的
          required: true
        - label: 我并未在议题中发现与此相关的
          required: true
        - label: 我确信我所提供的建议是可行的
          required: true